
# Kubernetes Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 2 # Run two pods for high availability
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service-container
        image: my-dockerhub/auth:latest
        ports:
        - containerPort: 5000 # The port the application listens on inside the container
---
# Kubernetes Service configuration to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  # This selector ensures the service routes traffic to pods with the 'app: auth-service' label
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on
      targetPort: 5000 # The port to forward traffic to on the pods
  # Exposes the service on an external IP, using the cloud provider's load balancer
  type: LoadBalancer
