
# Kubernetes Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
  labels:
    app: frontend-app
spec:
  replicas: 2 # Run two pods for high availability
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app-container
        image: my-repo/frontend:v2
        ports:
        - containerPort: 5000 # The port the application listens on inside the container
---
# Kubernetes Service configuration to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  # This selector ensures the service routes traffic to pods with the 'app: frontend-app' label
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on
      targetPort: 5000 # The port to forward traffic to on the pods
  # Exposes the service on an external IP, using the cloud provider's load balancer
  type: LoadBalancer
