
# Kubernetes Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 2 # Run two pods for high availability
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-container
        image: my-org/user-service:1.1
        ports:
        - containerPort: 5000 # The port the application listens on inside the container
---
# Kubernetes Service configuration to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  # This selector ensures the service routes traffic to pods with the 'app: user-service' label
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on
      targetPort: 5000 # The port to forward traffic to on the pods
  # Exposes the service on an external IP, using the cloud provider's load balancer
  type: LoadBalancer
